### ISSUE TITLE
Node.js FS error

### ISSUE THREAD

**Issue by aoaochifan** [bugra9/gdal3.js#29]
when is use Gdal.open() with node.js，there is some error output :

gdal stdout: Error: FS error
and
gdal stderr: Error: Fs error

windows10 + node.js v16.14.0

**Comment by bugra9** [comment]
Hi. If you try to open a file in the same directory like `Gdal.open('sample.geojson')`, you may get filesystem errors. It is a bug and I fixed it. You can try 2.0.2 version or `Gdal.open('./sample.geojson')`.
