### ISSUE TITLE
Observable example

### ISSUE THREAD

**Issue by neocarto** [bugra9/gdal3.js#33]
An example explaining how to import and use gdal3.js within [Observable](https://observablehq.com/) would be useful.

**Comment by TomBor** [comment]
Definitely not easy, but @mootari succeed.
See [observable forum](https://talk.observablehq.com/t/unable-to-import-gdal3-js-a-gdal-port/6732) and the notebook, [Hello gdal3.js](https://observablehq.com/@tombor/hello-gdal3?debug&dev&noworker)
