### ISSUE TITLE
Change License to something more permissive

### ISSUE THREAD

**Issue by amalic** [bugra9/gdal3.js#36]
GPL is too restrictive and will not work for most users. MIT, AGPL, or Apache License would be much cooler.

**Comment by bugra9** [comment]
Hi @amalic, sorry for replying so late.

Gdal3.js compiles with Geos and Spatialite. Both libraries are licensed with LGPL. Since I don't understand much about licensing and don't want to violate any licenses, I licensed it under the GPL.

What do you think about LGPL?

**Comment by ilyaly** [comment]
Hi!

LGPL sounds just great!

**Comment by bugra9** [comment]
@ilyaly, I changed the license from GPL to LGPL with the new version.

**Comment by ilyaly** [comment]
@bugra9 , thank you very much, that should really extend the audience of this beatiful library!

**Comment by amalic** [comment]
LGPL.is perfect!
