### ISSUE TITLE
I won't support it dxf to geojson？

### ISSUE THREAD

**Issue by lq0910** [bugra9/gdal3.js#38]
![image](https://user-images.githubusercontent.com/19302074/180122219-52d37215-b027-4fdf-a643-a896d50af453.png)

**Comment by bugra9** [comment]
dxf to geojson translation supported. https://gdal.org/drivers/vector/dxf.html

Is there an issue with the translation?

**Comment by lq0910** [comment]
dxf to geojson translation supported. https://gdal.org/drivers/vector/dxf.html

Is there an issue with the translation?
