### ISSUE TITLE
gdal stderr: Warning 1: Recode from CP936 to UTF-8 failed with the error: "Invalid argument".

### ISSUE THREAD

**Issue by lq0910** [bugra9/gdal3.js#39]
gdal stderr: Warning 1: Recode from CP936 to UTF-8 failed with the error: "Invalid argument".

![image](https://user-images.githubusercontent.com/19302074/180215530-e2a56315-4334-44f1-ac68-3e87900e0a66.png)

**Comment by bugra9** [comment]
Hi @lq0910 ,

Can you share additional information such as sample data, input format, output format?

**Comment by lq0910** [comment]
sample data：[http://sky.test.teamy.cn/assets/kj.dxf](http://sky.test.teamy.cn/assets/kj.dxf)  
dxf to geojson

**Comment by lq0910** [comment]
sample data：[http://sky.test.teamy.cn/assets/kj.dxf](http://sky.test.teamy.cn/assets/kj.dxf)  
dxf to geojson

**Comment by lq0910** [comment]
@bugra9  
![image](https://user-images.githubusercontent.com/19302074/180940841-099e27c8-c481-4996-9b2c-84ceda52e58e.png)

![image](https://user-images.githubusercontent.com/19302074/180940984-6224aacd-2e06-40d4-819c-7a04422b6e0f.png)

**Comment by lq0910** [comment]
I tried to change the encoding mode of DXF file to UTF-8, and the conversion was successful

**Comment by lq0910** [comment]
![image](https://user-images.githubusercontent.com/19302074/180941598-f54c0c3f-7cba-4299-b8ae-4cc02b935e13.png)

**Comment by bugra9** [comment]
@lq0910, Emscripten/Musl iconv does not support CP936.
https://github.com/emscripten-core/musl/blob/master/src/locale/iconv.c
https://wiki.musl-libc.org/functional-differences-from-glibc.html

> iconv
> The iconv implementation musl is very small and oriented towards being unobtrusive to static link. Its character set/encoding coverage is very strong for its size, but not comprehensive like glibc’s. In particular:
> - Many legacy double-byte and multi-byte East Asian encodings are supported only as the source charset, not the destination charset. JIS-based ones are supported as the destination as of version 1.1.19.
> - Conversion to ISO-2022-JP is stateless and produces shifts in/out of nondefault states around each character.
> - Transliterations (//TRANSLIT suffix) are not supported.
> - Converting to legacy 8-bit charsets is significantly slower than converting from them.
> - Prior to version 1.1.19, conversions from plain UTF-16 or UTF-32 without an explicit endianness assumed big endian and did not honor BOM. Now they honor BOM, but BOM is never produced in output.
> - Misleading, deprecated charset aliases like UNICODE as an alias for UCS-2 are not supported. The IANA preferred MIME charset names should be used instead.
> - Contrary to POSIX, glibc iconv generates EILSEQ when a character is not representable in the destination charset. musl, in accordance with POSIX, performs an implementation-defined conversion and returns the number of such inexact conversions performed. At present, it replaces the character with an asterisk, but something akin to glibc’s //TRANSLIT mode may be substituted in the future. Code written assuming the glibc semantics (error when no exact conversion is possible) may need to be tuned to work well on musl and other conforming iconv implementations.

So I added GNU libiconv and used it instead of Emscripten/Musl libiconv in new version 2.3.0. Can you try this version?

**Comment by lq0910** [comment]
OK, thank you very much. I'll try the new version

**Comment by lq0910** [comment]
OK, thank you very much. I'll try the new version

**Comment by lq0910** [comment]
The problem of the new version has been solved. It's great!
