### ISSUE TITLE
--config options

### ISSUE THREAD

**Issue by disarticulate** [bugra9/gdal3.js#40]
Not sure if this is a ogr2ogr a problem or related to this, but

```
gdal3.js:1 gdal stderr: ERROR 6: Unknown option name '--config'
```

When trying to set options here:  https://gdal.org/user/configoptions.html#list-config-options as described here: https://gdal.org/programs/vector_common_options.html#vector-common-options

**Comment by bugra9** [comment]
Hi @disarticulate,

In the new version I will add a field that these configurations can be entered. A new version will be released in a few days.

**Comment by disarticulate** [comment]
Appreciate the effort, everything else seems functional.

**Comment by bugra9** [comment]
@disarticulate, I released new version. Can you try this version?

**Comment by disarticulate** [comment]
should have an answer this weekend, thanks!

**Comment by disarticulate** [comment]
this appears to be working. got another issues though, but will open a different issue
