### ISSUE TITLE
Unknown option name '-a_ullr'

### ISSUE THREAD

**Issue by mumumi** [bugra9/gdal3.js#53]
When converting a png file without srs to a tif file with srs, we can use the command:
gdal_translate in.png out.tif -a_srs EPSG:4326 -a_ullr ulx uly lrx lry
ERROR 6: Unknown option name '-a_ullr' was thrown from gdal3.js

**Comment by mumumi** [comment]
Or any way to set coordinateTransform of a dataset?

**Comment by you-knowww** [comment]
Hello, I had the same issue and figured this out after much trial and error. The syntax for -a_ullr is like this:
`[ '-of', 'PDF', '-a_srs', 'EPSG:4326', '-a_ullr', ulx.toString(), uly.toString(), lrx.toString(), lry.toString()]`

**Comment by bugra9** [comment]
@you-knowww, thanks for the solution.
