### ISSUE TITLE
wasm unsupported MIME type

### ISSUE THREAD

**Issue by delebash** [bugra9/gdal3.js#54]
Just info on wasm

If you get this error then you need to add mime type wasm to your server.

for .htaccess add below line

AddType application/wasm wasm

For me I am using Namecheap shared hosting and even after adding the correct mime type gdal would not initialize and just hung trying to load.

I am using the Vue + Vite setup.

Not sure what is wrong but to work around the problem I just used the cdn method and all is well.

Thanks for making gdal for the web!!

**Comment by bugra9** [comment]
@delebash, thanks for the information.
