### ISSUE TITLE
Cannot set property location of #<WorkerGlobalScope> which has only a getter

### ISSUE THREAD

**Issue by lq0910** [bugra9/gdal3.js#59]
![image](https://user-images.githubusercontent.com/19302074/229354997-d2265dc4-414b-45ec-adcc-d78c981298a3.png)

In the Electron vue project

**Comment by bugra9** [comment]
Hi @lq0910,

Can you share more information?

**Comment by lq0910** [comment]
已收到。我会马上查看。

**Comment by lq0910** [comment]
已收到。我会马上查看。
