### ISSUE TITLE
How to access gdal stderr from ogr2ogr

### ISSUE THREAD

**Issue by informatter** [bugra9/gdal3.js#63]
Hi guys,
I am wondering if its possible to access the gdal stderr error messages from ogr2ogr ? Currently they are just being logged to the console.

Thanks

**Comment by bugra9** [comment]
Hi @informatter,

You can set the log and error handler using config in v2.6.0.
https://gdal3.js.org/docs/global.html#initGdalJs

**Comment by informatter** [comment]
@bugra9 thanks! 👍

**Comment by bugra9** [comment]
You are welcome
