### ISSUE TITLE
Update to GDAL 3.8.3

### ISSUE THREAD

**Issue by rouault** [bugra9/gdal3.js#64]
Hi,

just remainding that GDAL 3.8.0 to 3.8.2 had a few annoying regressions in ogr2ogr workflows from GeoPackage or FlatGeobuf to other formats that have been fixed in 3.8.3

**Comment by bugra9** [comment]
Hi @rouault,

Thanks for reminding me, I upgraded the Gdal version to 3.8.3 and released the new version. Also, thank you for the effort you put into Gdal.
