### ISSUE TITLE
How to check srs

### ISSUE THREAD

**Issue by phucnd1303** [bugra9/gdal3.js#65]
Hi, 
I get an issue when processing .dxf file

```
gdal stderr: ERROR 1: Can't transform coordinates, source layer has no
gdal stderr: coordinate system.  Use -s_srs to set one.
gdal stderr: ERROR 1: Terminating translation prematurely after failed
gdal stderr: translation from sql statement.
gdal stderr: ERROR 10: Pointer 'hDS' is NULL in 'GDALGetFileList'.
gdal stderr:
```

I know this issue occurs because this file doesn't have srs, so how I can use gdal3 to check srs? I see gdal library we can get srs but in gdal3 I dont know how to get that to check null or not. Please help me

**Comment by bugra9** [comment]
Hi @phucnd1303,

After opening the file, there is information about the dataset under `datasets[].info`. You can check the `layers[].geometryFields[].coordinateSystem` field.

![image](https://github.com/bugra9/gdal3.js/assets/2475497/ff4323e9-5973-4dcd-8cde-7645eab12b02)

**Comment by phucnd1303** [comment]
Thank you so much! @bugra9
